number_unit:
  zero: 0
  one: 1
  two: 2
  three: 3
  four: 4
  five: 5
  six: 6
  seven: 7
  eight: 8
  nine: 9
  ten: 10
  eleven: 11
  twelve: 12
  thirteen: 13
  fourteen: 14
  fifteen: 15
  sixteen: 16
  seventeen: 17
  eighteen: 18
  nineteen: 19
  twenty: 20
  thirty: 30
  forty: 40
  fifty: 50
  sixty: 60
  seventy: 70
  eighty: 80
  ninety: 90
  hundred: 100
  thousand: 1000
  million: 1000000
  billion: 1000000000
  trillion: 1000000000000

number_low:
  - zero
  - one
  - two
  - three
  - four
  - five
  - six
  - seven
  - eight
  - nine
  - ten
  - eleven
  - twelve
  - thirteen
  - fourteen
  - fifteen
  - sixteen
  - seventeen
  - eighteen
  - nineteen

unit_ten_low:
  - zero
  - ten
  - twenty
  - thirty
  - forty
  - fifty
  - sixty
  - seventy
  - eighty
  - ninety

unit_low:
  - thousand
  - million
  - billion
  - trillion


number_up:
  - zero
  - one
  - two
  - three
  - four
  - five
  - six
  - seven
  - eight
  - nine
  - eleven
  - twelve
  - thirteen
  - fourteen
  - fifteen
  - sixteen
  - seventeen
  - eighteen
  - nineteen

max_len: 15